apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-broker
  labels:
    app: kafka-broker
    component: kafka-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-broker
        component: kafka-broker-c
    spec:
      containers:
      - name: kafka-broker
        image: confluentinc/cp-kafka:5.3.1
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka-broker:9092
          - name: ENABLE_AUTO_EXTEND
            value: "true"
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "999999999"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: kafka-zk:2181
