apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: arm32v7/rabbitmq:3.6-management
        name: rabbitmq
        ports:
        - name: data
          containerPort: 5672
        - name: management
          containerPort: 15672
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
          requests:
            cpu: 0.5
            memory: 512Mi

