apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 4Gi
