== Spring Cloud Data Flow Server Core

The `spring-cloud-dataflow-server-core` subproject of `spring-cloud-dataflow` provides a common
REST API and UI that can be used to create a Data Flow Server for a particular deployment
environment when combined with an implementation of the `spring-cloud-deployer` SPI for that
environment.

The REST API includes a `StreamDefinitionController` and `TaskDefinitionController` that manage
stream and task definitions by delegating to the `StreamDefinitionRepository` and
`TaskDefinitionRepository`, respectively. The `StreamDeploymentController` and
`TaskDeploymentController` delegate to the `AppDeployer` and `TaskLauncher` provided by the
underlying `spring-cloud-deployer` SPI implementation. Other controllers provide endpoints for
managing the `AppRegistry`, viewing counters, etc.

For a simple getting-started experience, see the `spring-cloud-dataflow-server-local` (sibling)
project. The build for that project produces a boot-executable `LocalDataFlowServer` that relies on
an implementation of the Spring Cloud Deployer SPI that launches each stream app as a new JVM
process on the same host as the `LocalDataFlowServer` itself. By default the local server is
auto-populated with apps generated from the
link:https://github.com/spring-cloud/spring-cloud-stream-app-starters[`spring-cloud-stream-app-starters`]
project.

==== Embedded Atlas Metrics Server
To start SCDF with an embedded Atlas server (https://github.com/Netflix/atlas/wiki) pass  the following
SCDF server properties:

```
--spring.cloud.dataflow.metrics.atlas.server.enabled=true
--spring.cloud.dataflow.metrics.collector.uri=http://localhost:7101
--spring.cloud.dataflow.applicationProperties.stream.management.metrics.export.atlas.enabled=true
```
The `spring.cloud.dataflow.metrics.atlas.server.enabled=true` would start an embedded Atlas server
at `http://localhost:7101`. It would also replace the `MetricController.java` by the `AtlasMetricsController`.
Later uses the embedded Atlas server (as a metric collector)
to serve metrics to the SCDF-UI. The `spring.cloud.dataflow.metrics.collector.uri` instructs
the `AtlasMetricsCollector` how to access the Atlas Server.
The `spring.cloud.dataflow.applicationProperties.stream.management.metrics.export.atlas.enabled` property will enable
the atlas metrics repository for all SCSt apps that have the metrics-registry-atlas on the classpath.

Make sure that yor SCSt 2.0 applications are compiled with the following auto-starter dependency:

```
<groupId>org.springframework.cloud.stream.app.micrometer</groupId>
<artifactId>spring-cloud-stream-starter-common-metrics-tags</artifactId>
<version>1.0-SNAPSHOT</version>
```

That comes from: https://github.com/tzolov/spring-cloud-stream-starter-common-metrics-tags
The `spring-cloud-stream-starter-common-metrics-tags` injects common SCDF tags to the SCSt app metrics. tags such as

```
	stream -> spring.cloud.dataflow.stream.name
	applicationName -> spring.cloud.dataflow.stream.app.label
	instanceIndex -> instance.index
	applicationGuid -> spring.cloud.application.guid
	applicationType -> spring.cloud.dataflow.stream.app.type
```

The `spring-cloud-stream-starter-common-metrics-tags` also disables all micrometer registries by default. E.g. the
presence of the micrometer registry on the classpath will not activate it unless it explicitly enabled by the
`spring.cloud.dataflow.metrics.<MonitoringSystem>.server.enabled=true` property.





